-- Matugen generated colorscheme
-- This file is auto-generated by matugen

local M = {}

M.colors = {
  -- Base colors
  background = "#1a1111",
  foreground = "#f0dedd",
  surface = "#1a1111",
  surface_variant = "#524342",
  
  -- Primary colors
  primary = "#ffb3b1",
  primary_container = "#733333",
  on_primary = "#571d1f",
  on_primary_container = "#ffdad8",
  
  -- Secondary colors
  secondary = "#e6bdbb",
  secondary_container = "#5d3f3e",
  on_secondary = "#442929",
  on_secondary_container = "#ffdad8",
  
  -- Tertiary colors
  tertiary = "#e4c18d",
  tertiary_container = "#5a4319",
  on_tertiary = "#412d05",
  on_tertiary_container = "#ffdeab",
  
  -- Error colors
  error = "#ffb4ab",
  error_container = "#93000a",
  on_error = "#690005",
  on_error_container = "#ffdad6",
  
  -- Surface colors
  on_surface = "#f0dedd",
  on_surface_variant = "#d7c1c0",
  outline = "#a08c8b",
  outline_variant = "#524342",
  
  -- Inverse colors
  inverse_surface = "#f0dedd",
  inverse_on_surface = "#382e2d",
  inverse_primary = "#904a49",
  
  -- Shadow and scrim
  shadow = "#000000",
  scrim = "#000000",
}

function M.setup()
  vim.cmd("hi clear")
  if vim.fn.exists("syntax_on") then
    vim.cmd("syntax reset")
  end

  vim.o.termguicolors = true
  vim.g.colors_name = "matugen"

  local c = M.colors

  -- Editor UI
  vim.api.nvim_set_hl(0, "Normal", { fg = c.foreground, bg = c.background })
  vim.api.nvim_set_hl(0, "NormalFloat", { fg = c.foreground, bg = c.surface })
  vim.api.nvim_set_hl(0, "FloatBorder", { fg = c.outline, bg = c.surface })
  vim.api.nvim_set_hl(0, "CursorLine", { bg = c.surface_variant })
  vim.api.nvim_set_hl(0, "CursorLineNr", { fg = c.primary, bold = true })
  vim.api.nvim_set_hl(0, "LineNr", { fg = c.outline_variant })
  vim.api.nvim_set_hl(0, "SignColumn", { bg = c.background })
  vim.api.nvim_set_hl(0, "StatusLine", { fg = c.on_surface, bg = c.surface })
  vim.api.nvim_set_hl(0, "StatusLineNC", { fg = c.outline, bg = c.surface })
  vim.api.nvim_set_hl(0, "TabLine", { fg = c.on_surface_variant, bg = c.surface })
  vim.api.nvim_set_hl(0, "TabLineFill", { bg = c.surface })
  vim.api.nvim_set_hl(0, "TabLineSel", { fg = c.on_primary_container, bg = c.primary_container, bold = true })
  vim.api.nvim_set_hl(0, "Visual", { bg = c.primary_container })
  vim.api.nvim_set_hl(0, "Search", { fg = c.on_secondary_container, bg = c.secondary_container })
  vim.api.nvim_set_hl(0, "IncSearch", { fg = c.on_tertiary_container, bg = c.tertiary_container })
  vim.api.nvim_set_hl(0, "Pmenu", { fg = c.on_surface, bg = c.surface })
  vim.api.nvim_set_hl(0, "PmenuSel", { fg = c.on_primary_container, bg = c.primary_container })
  vim.api.nvim_set_hl(0, "PmenuSbar", { bg = c.surface_variant })
  vim.api.nvim_set_hl(0, "PmenuThumb", { bg = c.outline })
  vim.api.nvim_set_hl(0, "WinSeparator", { fg = c.outline_variant })
  vim.api.nvim_set_hl(0, "VertSplit", { fg = c.outline_variant })

  -- Syntax highlighting
  vim.api.nvim_set_hl(0, "Comment", { fg = c.outline, italic = true })
  vim.api.nvim_set_hl(0, "Constant", { fg = c.tertiary })
  vim.api.nvim_set_hl(0, "String", { fg = c.secondary })
  vim.api.nvim_set_hl(0, "Character", { fg = c.secondary })
  vim.api.nvim_set_hl(0, "Number", { fg = c.tertiary })
  vim.api.nvim_set_hl(0, "Boolean", { fg = c.tertiary })
  vim.api.nvim_set_hl(0, "Float", { fg = c.tertiary })
  vim.api.nvim_set_hl(0, "Identifier", { fg = c.on_surface })
  vim.api.nvim_set_hl(0, "Function", { fg = c.primary })
  vim.api.nvim_set_hl(0, "Statement", { fg = c.primary, bold = true })
  vim.api.nvim_set_hl(0, "Conditional", { fg = c.primary })
  vim.api.nvim_set_hl(0, "Repeat", { fg = c.primary })
  vim.api.nvim_set_hl(0, "Label", { fg = c.primary })
  vim.api.nvim_set_hl(0, "Operator", { fg = c.on_surface_variant })
  vim.api.nvim_set_hl(0, "Keyword", { fg = c.primary, bold = true })
  vim.api.nvim_set_hl(0, "Exception", { fg = c.error })
  vim.api.nvim_set_hl(0, "PreProc", { fg = c.tertiary })
  vim.api.nvim_set_hl(0, "Include", { fg = c.primary })
  vim.api.nvim_set_hl(0, "Define", { fg = c.primary })
  vim.api.nvim_set_hl(0, "Macro", { fg = c.tertiary })
  vim.api.nvim_set_hl(0, "Type", { fg = c.secondary })
  vim.api.nvim_set_hl(0, "StorageClass", { fg = c.primary })
  vim.api.nvim_set_hl(0, "Structure", { fg = c.secondary })
  vim.api.nvim_set_hl(0, "Special", { fg = c.tertiary })
  vim.api.nvim_set_hl(0, "SpecialChar", { fg = c.tertiary })
  vim.api.nvim_set_hl(0, "Tag", { fg = c.primary })
  vim.api.nvim_set_hl(0, "Delimiter", { fg = c.on_surface_variant })
  vim.api.nvim_set_hl(0, "SpecialComment", { fg = c.outline, bold = true })
  vim.api.nvim_set_hl(0, "Debug", { fg = c.error })
  vim.api.nvim_set_hl(0, "Underlined", { fg = c.primary, underline = true })
  vim.api.nvim_set_hl(0, "Error", { fg = c.error, bold = true })
  vim.api.nvim_set_hl(0, "Todo", { fg = c.tertiary, bold = true })

  -- Diagnostics
  vim.api.nvim_set_hl(0, "DiagnosticError", { fg = c.error })
  vim.api.nvim_set_hl(0, "DiagnosticWarn", { fg = c.tertiary })
  vim.api.nvim_set_hl(0, "DiagnosticInfo", { fg = c.primary })
  vim.api.nvim_set_hl(0, "DiagnosticHint", { fg = c.secondary })
  vim.api.nvim_set_hl(0, "DiagnosticUnderlineError", { undercurl = true, sp = c.error })
  vim.api.nvim_set_hl(0, "DiagnosticUnderlineWarn", { undercurl = true, sp = c.tertiary })
  vim.api.nvim_set_hl(0, "DiagnosticUnderlineInfo", { undercurl = true, sp = c.primary })
  vim.api.nvim_set_hl(0, "DiagnosticUnderlineHint", { undercurl = true, sp = c.secondary })

  -- Git signs
  vim.api.nvim_set_hl(0, "GitSignsAdd", { fg = c.secondary })
  vim.api.nvim_set_hl(0, "GitSignsChange", { fg = c.tertiary })
  vim.api.nvim_set_hl(0, "GitSignsDelete", { fg = c.error })

  -- Treesitter
  vim.api.nvim_set_hl(0, "@variable", { fg = c.on_surface })
  vim.api.nvim_set_hl(0, "@variable.builtin", { fg = c.tertiary })
  vim.api.nvim_set_hl(0, "@variable.parameter", { fg = c.on_surface_variant })
  vim.api.nvim_set_hl(0, "@variable.member", { fg = c.on_surface })
  vim.api.nvim_set_hl(0, "@constant", { fg = c.tertiary })
  vim.api.nvim_set_hl(0, "@constant.builtin", { fg = c.tertiary, bold = true })
  vim.api.nvim_set_hl(0, "@module", { fg = c.secondary })
  vim.api.nvim_set_hl(0, "@string", { fg = c.secondary })
  vim.api.nvim_set_hl(0, "@character", { fg = c.secondary })
  vim.api.nvim_set_hl(0, "@number", { fg = c.tertiary })
  vim.api.nvim_set_hl(0, "@boolean", { fg = c.tertiary })
  vim.api.nvim_set_hl(0, "@function", { fg = c.primary })
  vim.api.nvim_set_hl(0, "@function.builtin", { fg = c.primary, bold = true })
  vim.api.nvim_set_hl(0, "@function.macro", { fg = c.tertiary })
  vim.api.nvim_set_hl(0, "@keyword", { fg = c.primary, bold = true })
  vim.api.nvim_set_hl(0, "@keyword.function", { fg = c.primary })
  vim.api.nvim_set_hl(0, "@keyword.operator", { fg = c.primary })
  vim.api.nvim_set_hl(0, "@keyword.return", { fg = c.primary, bold = true })
  vim.api.nvim_set_hl(0, "@type", { fg = c.secondary })
  vim.api.nvim_set_hl(0, "@type.builtin", { fg = c.secondary, bold = true })
  vim.api.nvim_set_hl(0, "@property", { fg = c.on_surface })
  vim.api.nvim_set_hl(0, "@operator", { fg = c.on_surface_variant })
  vim.api.nvim_set_hl(0, "@punctuation.delimiter", { fg = c.on_surface_variant })
  vim.api.nvim_set_hl(0, "@punctuation.bracket", { fg = c.on_surface_variant })
  vim.api.nvim_set_hl(0, "@comment", { fg = c.outline, italic = true })
  vim.api.nvim_set_hl(0, "@tag", { fg = c.primary })
  vim.api.nvim_set_hl(0, "@tag.attribute", { fg = c.secondary })
  vim.api.nvim_set_hl(0, "@tag.delimiter", { fg = c.on_surface_variant })

  -- LSP semantic tokens
  vim.api.nvim_set_hl(0, "@lsp.type.namespace", { fg = c.secondary })
  vim.api.nvim_set_hl(0, "@lsp.type.type", { fg = c.secondary })
  vim.api.nvim_set_hl(0, "@lsp.type.class", { fg = c.secondary })
  vim.api.nvim_set_hl(0, "@lsp.type.enum", { fg = c.secondary })
  vim.api.nvim_set_hl(0, "@lsp.type.interface", { fg = c.secondary })
  vim.api.nvim_set_hl(0, "@lsp.type.struct", { fg = c.secondary })
  vim.api.nvim_set_hl(0, "@lsp.type.parameter", { fg = c.on_surface_variant })
  vim.api.nvim_set_hl(0, "@lsp.type.variable", { fg = c.on_surface })
  vim.api.nvim_set_hl(0, "@lsp.type.property", { fg = c.on_surface })
  vim.api.nvim_set_hl(0, "@lsp.type.enumMember", { fg = c.tertiary })
  vim.api.nvim_set_hl(0, "@lsp.type.function", { fg = c.primary })
  vim.api.nvim_set_hl(0, "@lsp.type.method", { fg = c.primary })
  vim.api.nvim_set_hl(0, "@lsp.type.macro", { fg = c.tertiary })
  vim.api.nvim_set_hl(0, "@lsp.type.decorator", { fg = c.tertiary })

  -- Telescope
  vim.api.nvim_set_hl(0, "TelescopeBorder", { fg = c.outline, bg = c.surface })
  vim.api.nvim_set_hl(0, "TelescopeNormal", { fg = c.on_surface, bg = c.surface })
  vim.api.nvim_set_hl(0, "TelescopeSelection", { fg = c.on_primary_container, bg = c.primary_container })
  vim.api.nvim_set_hl(0, "TelescopeMatching", { fg = c.primary, bold = true })

  -- Neo-tree
  vim.api.nvim_set_hl(0, "NeoTreeNormal", { fg = c.on_surface, bg = c.surface })
  vim.api.nvim_set_hl(0, "NeoTreeNormalNC", { fg = c.on_surface, bg = c.surface })
  vim.api.nvim_set_hl(0, "NeoTreeDirectoryIcon", { fg = c.primary })
  vim.api.nvim_set_hl(0, "NeoTreeDirectoryName", { fg = c.on_surface })
  vim.api.nvim_set_hl(0, "NeoTreeFileName", { fg = c.on_surface })
  vim.api.nvim_set_hl(0, "NeoTreeFileNameOpened", { fg = c.primary, bold = true })
  vim.api.nvim_set_hl(0, "NeoTreeGitModified", { fg = c.tertiary })
  vim.api.nvim_set_hl(0, "NeoTreeGitAdded", { fg = c.secondary })
  vim.api.nvim_set_hl(0, "NeoTreeGitDeleted", { fg = c.error })

  -- Which-key
  vim.api.nvim_set_hl(0, "WhichKey", { fg = c.primary })
  vim.api.nvim_set_hl(0, "WhichKeyGroup", { fg = c.secondary })
  vim.api.nvim_set_hl(0, "WhichKeyDesc", { fg = c.on_surface })
  vim.api.nvim_set_hl(0, "WhichKeySeparator", { fg = c.outline })
  vim.api.nvim_set_hl(0, "WhichKeyFloat", { bg = c.surface })
end

return M
