#include ~/.config/omarchy/current/theme/kitty.conf
# background            #232531
# foreground            #dcd6d6

# black
# color0  #232529
# color8  #787d87

# red
# color1  #848ea4
# color9  #b8becc

# green
# color2  #8b96ac
# color10 #c0c6d3

# yellow
# color3  #959fb1
# color11 #c9cfd9

# blue
# color4  #9ea7b8
# color12 #d2d7df

# magenta
# color5  #a7afbe
# color13 #dbdfe5

#cyan
# color6  #b0b7c5
# color14 #e5e7ec

#white
# color7  #d6d8dc
# color15 #dcd6d6

repaint_delay    8
input_delay      1
sync_to_monitor  yes

# Font
font_family MesloLGL Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        9.0

# Window
window_padding_width 10
window_padding_height 10
hide_window_decorations no
show_window_resize_notification no
confirm_os_window_close 0

# Keybindings
map ctrl+insert copy_to_clipboard
map shift+insert paste_from_clipboard

# Allow remote access
single_instance yes
allow_remote_control yes

# Aesthetics
cursor_shape block
enable_audio_bell no
background_opacity 0.85
background_blur 1

# A longer trail (30) creates more "frames" for the animation
cursor_trail 250

# We use a very low start number (0.01) and a high end number (1.0)
# This ensures the trail starts immediately and glides to a stop
#cursor_trail_decay 0.01 0.05

# This ensures every tiny movement is captured in the animation
cursor_trail_start_threshold 2

# Minimal Tab bar styling
tab_bar_edge                bottom
tab_bar_style               powerline
tab_powerline_style         slanted
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}


# BEGIN_KITTY_THEME
# Noctalia
include current-theme.conf
# END_KITTY_THEME