[colors.primary]
background = '#131314'
foreground = '#e4e2e3'
 
[colors.cursor]
text = '#e4e2e3'
cursor = '#c5c6cc' 
 
[colors.vi_mode_cursor]
text = '#131314'
cursor = '#bec7d9' 
 
[colors.search.matches]
foreground = '#45474c' 
background = '#cec2d8' 
 
[colors.search.focused_match]
foreground = '#45474c' 
background = '#bec7d9' 
 
[colors.footer_bar]
foreground = '#45474c' 
background = '#e4e2e3' 
 
[colors.hints.start]
foreground = '#45474c' 
background = '#c4c6ce' 
 
[colors.hints.end]
foreground = '#45474c' 
background = '#c4c6ce' 
 
[colors.selection]
text = '#131314'
background = '#bec7d9'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#bec7d9' 
yellow = '#565f6e' 
blue = '#bec7d9' 
magenta = '#cec2d8' 
cyan = '#c4c6ce' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 