color0 #131314
color1 #ffb4ab
color2 #bec7d9
color3 #c4c6ce
color4 #cec2d8
color5 #bec7d9
color6 #c4c6ce
color7 #e4e2e3
color8 #8f9096
color9 #ffb4ab
color10 #bec7d9
color11 #c4c6ce
color12 #cec2d8
color13 #bec7d9
color14 #c4c6ce
color15 #e4e2e3

cursor                #e4e2e3
cursor_text_color     #131314
background            #131314
foreground            #e4e2e3
selection_foreground  #c5c6cc
selection_background  #45474c
active_border_color   #bec7d9
inactive_border_color #45474c
url_color             #bec7d9
